config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += [
    path("", include("ecommerce-django.core.urls", namespace="core")),
]

ecommerce-django/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    HomeView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
)


app_name = "core"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "checkout/",
        TemplateView.as_view(template_name="checkout-page.html"),
        name="checkout",
    ),
    path("product/<slug>/", ItemDetailView.as_view(), name="product"),
    path("add-to-cart/<slug>/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<slug>/", remove_from_cart, name="remove-from-cart"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
]

ecommerce-django/sample_app/urls.py
from django.urls import path

### import your views
# from .views import index, article


## define your url here - see example below

# app_name = "<your_app_name>"
# urlpatterns = [
#     path("", index, name="index"),
#     path("<slug:slug>/", article, name="article"),
# ]

ecommerce-django/core/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


CATEGORY_CHOICES = (
    ("S", "Shirt"),
    ("SW", "Sport wear"),
    ("OW", "Outwear"),
)

LABEL_CHOICES = (
    ("P", "primary"),
    ("S", "secondary"),
    ("D", "danger"),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})

    def get_item_price(self):
        return self.discount_price if self.discount_price else self.price

    def __str__(self):
        return self.title


class OrderItem(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def get_order_item_price(self):
        return self.item.get_item_price() * self.quantity

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)

    def get_order_price(self):
        return sum(item.get_item_price() for item in self.items)

    def __str__(self):
        return self.user.username

ecommerce-django/sample_app/models.py
from django.db import models
from django.conf import settings

from autoslug import AutoSlugField

### register your mnodels here - see example below

# class Article(models.Model):
#     title = models.CharField(max_length=255)
#     slug = AutoSlugField(unique=True, always_update=False, populate_from="title")
#     abstract = models.TextField(max_length=512)
#     content = models.TextField(max_length=2048)
#     date_created = models.DateTimeField(auto_now_add=True)
#     author = models.ForeignKey(
#         to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

#     def __str__(self):
#         return f'{self.title}'

ecommerce-django/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

ecommerce-django/core/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from regex import D

from .models import Item, OrderItem, Order


def home(request):
    context = {"items": Item.objects.all()}
    return render(request, "home-page.html", context)


class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = "home-page.html"


class OrderSummaryView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
        except ObjectDoesNotExist:
            messages.info(self.request, "Your cart is empty")
            return redirect('core:home')
        context = {
            'order': order,
            'order_items': order.items.all(),
            }
        return render(self.request, "order_summary.html", context)


class ItemDetailView(DetailView):
    model = Item
    template_name = "product-page.html"


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False,
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "The item quantity was updated.")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
    return redirect("core:product", slug=slug)


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_item_qs = OrderItem.objects.filter(
        item=item,
        user=request.user,
        ordered=False,
    )
    if order_item_qs.exists():
        order = order_qs[0]
        order_item = order_item_qs[0]
        order_item.delete()
        messages.info(request, "The product was removed from your cart.")
        if not order.items.all().exists():
            order.delete()
    else:
        messages.info(request, "Error. the item was not in your cart.")
    return redirect("core:product", slug=slug)

ecommerce-django/sample_app/api/views.py
from rest_framework import viewsets

### import your models and serializers, example below
# from ..models import SampleModel
# from .serializers import SampleSerializer


# class SampleViewSet(viewsets.ReadOnlyModelViewSet):
#     queryset = SampleModel.objects.all()
#     serializer_class = SampleSerializer

ecommerce-django/sample_app/views.py
from operator import attrgetter
from django.shortcuts import render
from django.core.paginator import Paginator

### import your models
# from .models import Article

### define your views here - see example below

# def index(request):
#     articles = Article.objects.all().order_by('-date_created')
    
#     paginator = Paginator(articles, 5)
#     try:
#         page_number = request.GET.get('page')
#     except AttributeError:
#         page_number = 1
#     page_obj = paginator.get_page(page_number)
    
#     context = {
#         "articles": articles,
#         "page_obj": page_obj,        
#     }
#     return render(request, "blog/index.html", context)


# def article(request, slug):
#     article = Article.objects.get(slug=slug)
#     context = {
#         "article": article
#     }
#     return render(request, "blog/article.html", context)

ecommerce-django/templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    </style>
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container">
        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="#">
          <strong class="blue-text">MDB</strong>
        </a>
        <!-- Collapse -->
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect"
                 href="{% url 'core:checkout' %}"
                 target="_blank">Checkout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#" target="_blank">Products</a>
            </li>
          </ul>
          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link waves-effect" href={% url "core:order-summary" %}>
                  <span class="badge red z-depth-1 mr-1">{{ request.user | cart_item_count }}</span>
                  <i class="fas fa-shopping-cart"></i>
                  <span class="clearfix d-none d-sm-inline-block">Cart</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                  <span class="clearfix d-none d-sm-inline-block">Logout</span>
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                  <span class="clearfix d-none d-sm-inline-block">Login</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                  <span class="clearfix d-none d-sm-inline-block">Sign-up</span>
                </a>
              </li>              
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="pt-5 mt-3">
    <!-- Navbar -->
    {% if messages %}
      <div class="mt-5 pt-4">
        {% for message in messages %}<div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>{% endfor %}
      </div>
    {% endif %}
    {% block content %}
    {% endblock content %}
    </div>
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank">MDBootstrap.com</a>
      </div>
      <!--/.Copyright-->
    </footer>
    <!--/.Footer-->
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
    // Animations initialization
    new WOW().init();

    </script>
  </body>
</html>

ecommerce-django/templates/home-page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <!--Main layout-->
  <main>
    <div class="container pt-5">
      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>
        <!-- Collapse button -->
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#basicExampleNav"
                aria-controls="basicExampleNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>
          </ul>
          <!-- Links -->
          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2"
                     type="text"
                     placeholder="Search"
                     aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->
      </nav>
      <!--/.Navbar-->
      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        <div class="row wow fadeIn">
          {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">
              <!--Card-->
              <div class="card">
                <!--Card image-->
                <div class="view overlay">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                       class="card-img-top"
                       alt="">
                  <a href="{{ item.get_absolute_url }}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->
                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      </a>
                    </strong>
                  </h5>
                  <h4 class="font-weight-bold blue-text">
                    <strong>
                      {% if item.discount_price %}
                        {{ item.discount_price }}
                      {% else %}
                        {{ item.price }}
                      {% endif %}
                    </strong>
                  </h4>
                </div>
                <!--Card content-->
              </div>
              <!--Card-->
            </div>
          {% endfor %}
        </div>
      </section>
      <!--Section: Products v.3-->
      
       {% if is_paginated  %}
      <!--Pagination-->
     

      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"  aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}
    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

ecommerce-django/templates/order_summary.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <!--Main layout-->
  <main>
    {% if order %}
      <div class="container pt-5">
        <h2>Order Summary</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Item</th>
              <th scope="col">Quantity</th>
              <th scope="col">Unit Price</th>
              <th scope="col">Total Price</th>
            </tr>
          </thead>
          <tbody>
            {% for order_item in order_items %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                  <a href="{{ order_item.item.get_absolute_url }}">{{ order_item.item.title }}</a>
                </td>
                <td>{{ order_item.quantity }}</td>
                <td>{{ order_item.item.get_item_price }}</td>
                <td>{{ order_item.get_order_item_price }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
    {% endif %}
  </main>
  <!--Main layout-->
{% endblock content %}

ecommerce-django/templates/product-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <!--Content-->
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>
            <p class="lead">
              {% if item.discount_price %}
                <span class="mr-1">
                  <del>{{ item.price }}</del>
                </span>
                <span>{{ item.discount_price }}</span>
              {% else %}
                <span class="mr-1">{{ item.price }}</span>
              {% endif %}
            </p>
            <p class="lead font-weight-bold">Description</p>
            <p>{{ object.description }}</p>
            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}"
               class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}"
               class="btn btn-primary btn-md my-0 p">
              Remove from to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
          </div>
          <!--Content-->
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <hr>
      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.
          </p>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
               class="img-fluid"
               alt="">
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->
{% endblock content %}